[project]
name = "scubaduikers"
version = "3"
description = "scubaduikers de start van je duik"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.136.3",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "python-dotenv>=1.0.0",
    "sqlmodel>=0.0.38",
]
